const HTTP_OK = 200
const HTTP_SAVED = 201
const HTTP_UPDATED = 204
const HTTP_BAD_REQUEST = 400
const HTTP_UNPROCESSABLE_ENTITY = 422
const HTTP_UNAUTHORIZED = 401
const HTTP_FORBIDDEN = 403
const HTTP_NOT_FOUND = 404

const SEND_EMAIL_ERROR = 1303
const CONTENT_EMAIL_ERROR = 1304

module.exports = {
  HTTP_OK,
  HTTP_SAVED,
  HTTP_UPDATED,
  HTTP_BAD_REQUEST,
  HTTP_UNAUTHORIZED,
  HTTP_UNPROCESSABLE_ENTITY,
  HTTP_FORBIDDEN,
  HTTP_NOT_FOUND,
  CONTENT_EMAIL_ERROR,
  SEND_EMAIL_ERROR,
}
